#!/bin/sh
set -euo pipefail
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

projectRoot=$(git rev-parse --show-toplevel)

# If match FILES with *.js,jsx,ts,tsx,css, apply prettier
echo "$FILES" | grep -E ".*\.(js|jsx|ts|tsx|css)$" | xargs "${projectRoot}/node_modules/.bin/prettier" --write
# If match FILES with *.go, apply gofmt
echo "$FILES" | grep -E ".*\.go$" | xargs gofmt -w

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0
